
import type { LeaveRequest } from "./types";

export const mockLeaveRequests: LeaveRequest[] = [
    {
        id: 'LR001',
        userId: 'STU001',
        userName: 'Aarav Sharma',
        userRole: 'Student',
        type: 'Leave',
        startDate: '2024-08-05',
        endDate: '2024-08-05',
        reason: 'Family function',
        status: 'Approved',
        aiSummary: 'Attending a family function.',
    },
    {
        id: 'LR002',
        userId: 'STU002',
        userName: 'Diya Patel',
        userRole: 'Student',
        type: 'OD',
        startDate: '2024-08-10',
        endDate: '2024-08-11',
        reason: 'Attending a technical symposium at another college to present a paper on AI.',
        status: 'Pending HOD',
        aiSummary: 'Presenting a paper at a technical symposium.',
    },
    {
        id: 'LR003',
        userId: 'USR003',
        userName: 'Dr. Sameer Verma',
        userRole: 'Faculty',
        type: 'Leave',
        startDate: '2024-08-12',
        endDate: '2024-08-12',
        reason: 'Personal emergency, need to travel out of station.',
        status: 'Pending HOD',
        aiSummary: 'Traveling out of station for a personal emergency.',
    },
     {
        id: 'LR004',
        userId: 'STU004',
        userName: 'Priya Singh',
        userRole: 'Student',
        type: 'Leave',
        startDate: '2024-08-02',
        endDate: '2024-08-02',
        reason: 'Not feeling well, suffering from a fever.',
        status: 'Rejected',
        aiSummary: 'Sick with a fever.',
    },
     {
        id: 'LR005',
        userId: 'STU003',
        userName: 'Rohan Joshi',
        userRole: 'Student',
        type: 'OD',
        startDate: '2024-08-15',
        endDate: '2024-08-15',
        reason: 'Participating in the inter-college sports meet for basketball.',
        status: 'Pending Advisor',
        aiSummary: 'Participating in an inter-college basketball meet.',
    },
];
